#:schema ./.schemas/reuse.json
version = 1
SPDX-PackageName = "foundation-registry"
SPDX-PackageSupplier = "TTT Studios <no-reply@ttt.studios>"
SPDX-PackageDownloadLocation = "https://github.com/tttstudios/foundation-registry"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 TTT Studios"
SPDX-License-Identifier = "LicenseRef-Proprietary"
