#!/usr/bin/env bash
# lib/build-cli-launcher.sh — generate the ~/.local/bin/claude-account-<label>
# terminal launcher. Called by lib/install-instance.sh.
#
# Usage: build-cli-launcher.sh <label> <configDir> <userData> <launcherPath>
# Idempotent: writes atomically via mv, snapshots any existing file first.

set -euo pipefail

# shellcheck source=./common.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

main() {
  local label="$1" cdir="$2" udata="$3" out="$4"
  cma_validate_label "$label"

  [[ -n "$cdir" && -n "$udata" && -n "$out" ]] || cma_die "build-cli-launcher: missing args"

  local dir
  dir="$(dirname "$out")"
  mkdir -p "$dir"

  # Snapshot any existing launcher (undo path).
  if [[ -e "$out" ]]; then
    local snap
    snap="$(cma_backup_snapshot "$out" "cli-launcher-$label")"
    cma_dim "  snapshot: $snap"
  fi

  # The launcher: `open -na Claude.app --env CLAUDE_CONFIG_DIR=... --args --user-data-dir=...`
  # `open` accepts `--env` on this macOS which is what propagates CLAUDE_CONFIG_DIR
  # to the GUI Claude Desktop app. Any extra args passed to the launcher (`$@`)
  # forward to `Claude.app`'s embedded Claude Code CLI.
  local tmp
  tmp="$(mktemp "$out.XXXXXX")"
  cat > "$tmp" << LAUNCHER
#!/usr/bin/env bash
# claude-account-$label — terminal launcher for Claude Desktop instance '$label'.
# Generated by claude-multiacct — do not edit by hand; run \`claude-multiacct repair $label\` instead.

exec open -na /Applications/Claude.app \\
  --env "CLAUDE_CONFIG_DIR=$cdir" \\
  --args --user-data-dir="$udata" "\$@"
LAUNCHER
  chmod +x "$tmp"
  mv -f "$tmp" "$out"
  cma_ok "wrote $out"
}

main "$@"
