#!/usr/bin/env node
/**
 * Opt-in generator for a fork's sync-upstream GitHub Actions workflow.
 *
 * Reads a small JSON config from the caller's working directory
 * (`.sync-upstream.json`), substitutes placeholders into the template shipped
 * at `packages/shared/config/workflows/sync-upstream.<mode>.template.yml`, and
 * writes the result to `.github/workflows/sync-upstream.yml` in the caller's
 * working directory.
 *
 * Two modes:
 *   - `cross-owner` (default) — fork + upstream sit under different accounts,
 *     both remotes ride SSH with a shared deploy key. Placeholders:
 *     `${UPSTREAM_REPO_SSH}`, `${UPSTREAM_BRANCH}`, `${UPSTREAM_DEPLOY_KEY_SECRET}`.
 *   - `same-owner` — fork + upstream sit under the same account (GitHub
 *     refuses a shared deploy key); both remotes ride HTTPS with a repo-
 *     scoped `GH_TOKEN`. Placeholders: `${UPSTREAM_REPO_PATH}`,
 *     `${UPSTREAM_BRANCH}`. The path is derived from `upstreamRepoSsh`.
 *
 * Idempotent: on a re-run whose config yields byte-identical output, the CLI
 * is a no-op. If the target file exists and DOES NOT match, the CLI exits
 * non-zero to preserve local edits; pass `--force` to overwrite.
 *
 * The templates live under `packages/shared/config/` and are discovered via
 * paths relative to this script, so a fork that consumes `@foundation/sync`
 * through the workspace protocol also finds them without extra wiring.
 *
 * @module
 */

// The `${NAME}` placeholder literals used for substitution and the shell-var
// occurrences in error messages are NOT template-literal expressions — they
// are the very strings the tool matches or refers to. oxlint's
// `no-template-curly-in-string` is a false positive across this file.
/* oxlint-disable no-template-curly-in-string */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import * as v from "valibot";

/** Which auth topology the fork uses to reach its upstream. */
export const SYNC_UPSTREAM_MODES = ["cross-owner", "same-owner"] as const;
export type SyncUpstreamMode = (typeof SYNC_UPSTREAM_MODES)[number];

/** Valibot schema for `.sync-upstream.json`. */
const CONFIG_SCHEMA = v.object({
	mode: v.optional(v.picklist(SYNC_UPSTREAM_MODES), "cross-owner"),
	upstreamRepoSsh: v.pipe(v.string(), v.minLength(1)),
	upstreamBranch: v.pipe(v.string(), v.minLength(1)),
	deployKeySecret: v.optional(v.pipe(v.string(), v.minLength(1))),
});

/** Shape of `.sync-upstream.json` in the caller's cwd. */
export type OptInConfig = v.InferOutput<typeof CONFIG_SCHEMA>;

// Cross-field rule applied after the object schema runs. Kept out of the
// valibot pipe so it fires independently of the field-level checks — a
// payload that omits BOTH upstreamRepoSsh AND deployKeySecret surfaces both
// errors, not just the first one valibot found.
function crossFieldError(config: OptInConfig): string | null {
	if (config.mode === "cross-owner" && typeof config.deployKeySecret !== "string") {
		return "deployKeySecret is required when mode is 'cross-owner'";
	}
	return null;
}

const CONFIG_FILE = ".sync-upstream.json";
const OUTPUT_FILE = join(".github", "workflows", "sync-upstream.yml");

const TEMPLATE_DIR = join(import.meta.dirname, "..", "..", "..", "config", "workflows");

const TEMPLATE_FILES: Readonly<Record<SyncUpstreamMode, string>> = {
	"cross-owner": "sync-upstream.cross-owner.template.yml",
	"same-owner": "sync-upstream.same-owner.template.yml",
};

// Header prepended to the generated workflow. Carries the schema-ref for the
// OUTPUT location (`.github/workflows/…` -> `../../.schemas/github-workflow.json`)
// and a marker line pointing readers at the specific mode template that was
// consumed. The mode is threaded in so a reader of the generated file can jump
// straight to the source template file (not a `<mode>` placeholder).
function outputHeaderFor(mode: SyncUpstreamMode): string {
	return [
		"# yaml-language-server: $schema=../../.schemas/github-workflow.json",
		"# Generated by `pnpm sync-upstream:opt-in` from",
		`# \`packages/shared/config/workflows/sync-upstream.${mode}.template.yml\`.`,
		"# Regenerate after changing `.sync-upstream.json` or the template; a",
		"# hand edit here is preserved (the CLI exits with conflict) until you",
		"# rerun with `--force`.",
		"",
	].join("\n");
}

// Extract `owner/repo` from a GitHub SSH clone URL. The same-owner template
// composes an HTTPS URL as `https://x-access-token:<pat>@github.com/${path}.git`,
// so the path here is the middle segment without the `.git` suffix.
function deriveRepoPath(upstreamRepoSsh: string): string {
	const match = /^git@github\.com:(.+?)(?:\.git)?$/u.exec(upstreamRepoSsh);
	if (match === null || match[1] === undefined || match[1] === "") {
		throw new Error(
			`upstreamRepoSsh does not look like a GitHub SSH URL (${JSON.stringify(upstreamRepoSsh)}); expected git@github.com:<owner>/<repo>.git`,
		);
	}
	return match[1];
}

// Substitute placeholders into the template text. Literal `${NAME}` matches
// only; GHA's `${{ ... }}` expressions pass through because the outer braces
// do not match a placeholder start. The output header (schema-ref + marker)
// is prepended and threaded with the mode name so the generated file points
// at the specific template it came from.
export function substitute(template: string, config: OptInConfig): string {
	let body = template
		.replaceAll("${UPSTREAM_REPO_SSH}", config.upstreamRepoSsh)
		.replaceAll("${UPSTREAM_BRANCH}", config.upstreamBranch);
	if (config.mode === "same-owner") {
		body = body.replaceAll("${UPSTREAM_REPO_PATH}", deriveRepoPath(config.upstreamRepoSsh));
	} else {
		// cross-owner: deployKeySecret is required (checked in the schema).
		body = body.replaceAll("${UPSTREAM_DEPLOY_KEY_SECRET}", config.deployKeySecret ?? "");
	}
	return outputHeaderFor(config.mode) + body;
}

// Turn valibot issues + the cross-field rule into a stable one-line message
// that names EVERY offending field. valibot's default `error.message` only
// mentions the first issue, which would let a partial fix slip past a
// "throws with every missing field" test. The cross-field rule (mode ↔
// deployKeySecret) contributes `deployKeySecret` to the same list so the
// caller sees one sorted enumeration, not a joined clause.
function formatValidationError(
	issues: ReadonlyArray<v.BaseIssue<unknown>>,
	crossField: string | null,
): string {
	const fields = new Set<string>();
	for (const issue of issues) {
		for (const step of issue.path ?? []) {
			if (typeof step.key === "string" && step.key !== "") {
				fields.add(step.key);
			}
		}
	}
	if (crossField !== null) {
		fields.add("deployKeySecret");
	}
	return `is missing required string fields: ${[...fields].join(", ")}`;
}

// Parse and validate `.sync-upstream.json` from a caller-supplied working
// directory. Throws if the file is missing or the schema does not accept the
// parsed object (missing required field, wrong type, unknown mode) OR if the
// cross-field mode/deployKeySecret rule fails. Both categories surface in a
// single error message so a partly-invalid payload doesn't take two edit-
// and-retry cycles.
export function readConfig(cwd: string): OptInConfig {
	const path = join(cwd, CONFIG_FILE);
	if (!existsSync(path)) {
		throw new Error(
			`${CONFIG_FILE} not found in ${cwd}. See ADOPTING.md — "Opting into upstream sync".`,
		);
	}
	const raw = readFileSync(path, "utf8");
	const parsed = JSON.parse(raw) as unknown;
	const result = v.safeParse(CONFIG_SCHEMA, parsed);
	const fieldErrors = result.success ? [] : result.issues;
	// Run the cross-field check on the raw JSON so a payload that omits BOTH
	// upstreamRepoSsh AND deployKeySecret surfaces both errors, not just the
	// one valibot found first. Non-object input skips the check — there's no
	// `mode` to reason about.
	const objectShaped = parsed !== null && typeof parsed === "object" && !Array.isArray(parsed);
	const crossField = objectShaped
		? crossFieldError({
				...(parsed as Partial<OptInConfig>),
				mode: (parsed as { mode?: SyncUpstreamMode }).mode ?? "cross-owner",
			} as OptInConfig)
		: null;
	if (fieldErrors.length > 0 || crossField !== null) {
		throw new Error(`${CONFIG_FILE} ${formatValidationError(fieldErrors, crossField)}`);
	}
	// `result.success` is guaranteed here (fieldErrors would be non-empty
	// otherwise), so the else branch is unreachable in practice — leave the
	// non-null assertion off and rely on TypeScript's own narrowing.
	/* v8 ignore next 3 -- guarded above; result.success is provably true when both fieldErrors and crossField are empty */
	if (!result.success) {
		throw new Error(`${CONFIG_FILE} did not match the expected shape`);
	}
	return result.output;
}

/** Outcome of a write attempt. */
export type WriteOutcome = "written" | "unchanged" | "conflict";

// Idempotent write: create the target if missing, no-op on match, conflict on
// mismatch (unless `force` is true). Creates the parent directory as needed.
export function writeIdempotent(target: string, generated: string, force: boolean): WriteOutcome {
	if (!existsSync(target)) {
		mkdirSync(dirname(target), { recursive: true });
		writeFileSync(target, generated);
		return "written";
	}
	const current = readFileSync(target, "utf8");
	if (current === generated) {
		return "unchanged";
	}
	if (force) {
		writeFileSync(target, generated);
		return "written";
	}
	return "conflict";
}

// Read the shipped template for a mode. Extracted so tests can pin a fixture
// template without touching the real files.
export function readTemplate(mode: SyncUpstreamMode): string {
	return readFileSync(join(TEMPLATE_DIR, TEMPLATE_FILES[mode]), "utf8");
}

// CLI entry point. Side effects are abstracted so tests can drive it against
// a tmpdir with captured stdout/stderr. Returns the process exit code. The
// `template` argument, when omitted, delegates to `readTemplate(config.mode)`
// so a fixture template can bypass the real file lookup.
export function main(
	argv: readonly string[],
	cwd: string,
	log: (s: string) => void,
	err: (s: string) => void,
	template?: string,
): number {
	const force = argv.includes("--force");
	let config: OptInConfig;
	try {
		config = readConfig(cwd);
	} catch (error) {
		err(`opt-in-sync-upstream: ${(error as Error).message}\n`);
		return 1;
	}
	const resolvedTemplate = template ?? readTemplate(config.mode);
	const generated = substitute(resolvedTemplate, config);
	const target = join(cwd, OUTPUT_FILE);
	const outcome = writeIdempotent(target, generated, force);
	if (outcome === "written") {
		log(
			`opt-in-sync-upstream: wrote ${OUTPUT_FILE} from ${config.mode} template (${String(generated.length)} bytes)\n`,
		);
		return 0;
	}
	if (outcome === "unchanged") {
		log(`opt-in-sync-upstream: ${OUTPUT_FILE} matches generated output, no-op\n`);
		return 0;
	}
	err(
		`opt-in-sync-upstream: ${OUTPUT_FILE} exists and differs from the generated output. Re-run with --force to overwrite (this replaces local edits).\n`,
	);
	return 2;
}

// Run as CLI only when invoked as `node <this-script>` (mirrors schemas.ts).
// The body is exercised in production but not from the vitest worker
// (`import.meta.filename !== process.argv[1]` under vitest), so the coverage
// tool sees these six lines as untaken; the tests below cover `main()`
// directly against a tmpdir instead.
/* v8 ignore start -- CLI-entry block; main() is unit-tested against a tmpdir */
if (import.meta.filename === process.argv[1]) {
	const code = main(
		process.argv.slice(2),
		process.cwd(),
		(s) => process.stdout.write(s),
		(s) => process.stderr.write(s),
	);
	process.exit(code);
}
/* v8 ignore stop */
