#!/usr/bin/env node
/**
 * Opt-in generator for a fork's sync-upstream GitHub Actions workflow.
 *
 * Reads a small JSON config from the caller's working directory
 * (`.sync-upstream.json`), substitutes three placeholders into the template
 * shipped at `packages/shared/config/workflows/sync-upstream.template.yml`, and
 * writes the result to `.github/workflows/sync-upstream.yml` in the caller's
 * working directory.
 *
 * Idempotent: on a re-run whose config yields byte-identical output, the CLI
 * is a no-op. If the target file exists and DOES NOT match, the CLI exits
 * non-zero to preserve local edits; pass `--force` to overwrite.
 *
 * The template lives under `packages/shared/config/` and is discovered via a
 * path relative to this script, so a fork that consumes `@foundation/sync`
 * through the workspace protocol also finds it without extra wiring.
 *
 * @module
 */

// The `${NAME}` placeholder literals used for substitution and the shell-var
// occurrences in error messages are NOT template-literal expressions — they
// are the very strings the tool matches or refers to. oxlint's
// `no-template-curly-in-string` is a false positive across this file.
/* oxlint-disable no-template-curly-in-string */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

/** Shape of `.sync-upstream.json` in the caller's cwd. */
export type OptInConfig = {
	/** SSH URL of the upstream repo, e.g. `git@github.com:owner/upstream.git`. */
	readonly upstreamRepoSsh: string;
	/** Upstream branch to track, e.g. `main`. */
	readonly upstreamBranch: string;
	/** Repo-secret NAME (not value) holding the deploy key, e.g. `UPSTREAM_DEPLOY_KEY`. */
	readonly deployKeySecret: string;
};

const CONFIG_FILE = ".sync-upstream.json";
const OUTPUT_FILE = join(".github", "workflows", "sync-upstream.yml");

const TEMPLATE_PATH = join(
	import.meta.dirname,
	"..",
	"..",
	"..",
	"config",
	"workflows",
	"sync-upstream.template.yml",
);

// Header prepended to the generated workflow. Carries the schema-ref for the
// OUTPUT location (`.github/workflows/…` -> `../../.schemas/github-workflow.json`)
// and a marker line pointing readers at the template + regeneration command.
// Kept outside `substitute()` so the pure function stays testable without
// coupling to the schema layout.
const OUTPUT_HEADER = [
	"# yaml-language-server: $schema=../../.schemas/github-workflow.json",
	"# Generated by `pnpm sync-upstream:opt-in` from",
	"# `packages/shared/config/workflows/sync-upstream.template.yml`.",
	"# Regenerate after changing `.sync-upstream.json` or the template; a",
	"# hand edit here is preserved (the CLI exits with conflict) until you",
	"# rerun with `--force`.",
	"",
].join("\n");

// Substitute the three placeholders into the template text. Literal `${NAME}`
// matches only; GHA's `${{ ... }}` expressions pass through because the outer
// braces do not match a placeholder start. The output header (schema-ref +
// generation marker) is prepended.
export function substitute(template: string, config: OptInConfig): string {
	const body = template
		.replaceAll("${UPSTREAM_REPO_SSH}", config.upstreamRepoSsh)
		.replaceAll("${UPSTREAM_BRANCH}", config.upstreamBranch)
		.replaceAll("${UPSTREAM_DEPLOY_KEY_SECRET}", config.deployKeySecret);
	return OUTPUT_HEADER + body;
}

// Parse and validate `.sync-upstream.json` from a caller-supplied working
// directory. Throws if the file is missing or a required string field is
// blank/absent.
export function readConfig(cwd: string): OptInConfig {
	const path = join(cwd, CONFIG_FILE);
	if (!existsSync(path)) {
		throw new Error(
			`${CONFIG_FILE} not found in ${cwd}. See ADOPTING.md — "Opting into upstream sync".`,
		);
	}
	const raw = readFileSync(path, "utf8");
	const parsed = JSON.parse(raw) as Partial<OptInConfig>;
	const required: Array<keyof OptInConfig> = [
		"upstreamRepoSsh",
		"upstreamBranch",
		"deployKeySecret",
	];
	const missing = required.filter((k) => typeof parsed[k] !== "string" || parsed[k] === "");
	if (missing.length > 0) {
		throw new Error(`${CONFIG_FILE} is missing required string fields: ${missing.join(", ")}`);
	}
	return parsed as OptInConfig;
}

/** Outcome of a write attempt. */
export type WriteOutcome = "written" | "unchanged" | "conflict";

// Idempotent write: create the target if missing, no-op on match, conflict on
// mismatch (unless `force` is true). Creates the parent directory as needed.
export function writeIdempotent(target: string, generated: string, force: boolean): WriteOutcome {
	if (!existsSync(target)) {
		mkdirSync(dirname(target), { recursive: true });
		writeFileSync(target, generated);
		return "written";
	}
	const current = readFileSync(target, "utf8");
	if (current === generated) {
		return "unchanged";
	}
	if (force) {
		writeFileSync(target, generated);
		return "written";
	}
	return "conflict";
}

// Read the shipped template. Extracted so tests can pin a fixture template
// without touching the real file.
export function readTemplate(): string {
	return readFileSync(TEMPLATE_PATH, "utf8");
}

// CLI entry point. Side effects are abstracted so tests can drive it against
// a tmpdir with captured stdout/stderr. Returns the process exit code.
export function main(
	argv: readonly string[],
	cwd: string,
	log: (s: string) => void,
	err: (s: string) => void,
	template: string = readTemplate(),
): number {
	const force = argv.includes("--force");
	let config: OptInConfig;
	try {
		config = readConfig(cwd);
	} catch (error) {
		err(`opt-in-sync-upstream: ${(error as Error).message}\n`);
		return 1;
	}
	const generated = substitute(template, config);
	const target = join(cwd, OUTPUT_FILE);
	const outcome = writeIdempotent(target, generated, force);
	if (outcome === "written") {
		log(`opt-in-sync-upstream: wrote ${OUTPUT_FILE} (${generated.length} bytes)\n`);
		return 0;
	}
	if (outcome === "unchanged") {
		log(`opt-in-sync-upstream: ${OUTPUT_FILE} matches generated output, no-op\n`);
		return 0;
	}
	err(
		`opt-in-sync-upstream: ${OUTPUT_FILE} exists and differs from the generated output. Re-run with --force to overwrite (this replaces local edits).\n`,
	);
	return 2;
}

// Run as CLI only when invoked as `node <this-script>` (mirrors schemas.ts).
if (import.meta.filename === process.argv[1]) {
	const code = main(
		process.argv.slice(2),
		process.cwd(),
		(s) => process.stdout.write(s),
		(s) => process.stderr.write(s),
	);
	process.exit(code);
}
